import Head from 'next/head';
import Navbar from './Navbar';
import styles from "../styles/Home.module.css";

export default function Layout({ children, ...props }) {
  return (
    <div>
      <Head>
        <title>Lit x Livepeer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span>Lit x Livepeer Streaming!</span>
        </h1>

        <p className={styles.description}>
          Token Gating a Livepeer Stream with Lit Protocol
        </p>
        {children}
      </main>
      <footer className={styles.footer}>
        <a
          href="https://github.com/Salmandabbakuti"
          target="_blank"
          rel="noopener noreferrer"
        >
          © 2022 Salman Dabbakuti. Built with Lit & Livepeer
        </a>
      </footer>
    </div>
  );
}